/**
 * ○× quiz bank — the plaza's true/false questions.
 * ================================================
 *
 * Each entry is one statement. Players run to ○ if they think it is true and to × if they
 * think it is false; the reveal shows the answer and one line of explanation. Every
 * statement and explanation is written in Simplified Chinese, Japanese and English, and
 * the three must say exactly the same thing. Only the `id` travels on the wire; the
 * client looks the words up here.
 *
 * Adding a question: append a new entry at the end with a fresh kebab-case id
 * (`<category>-<short-slug>`). Never reuse, rename or renumber an id, and never flip the
 * `answer` of an existing one — rewrite it under a new id instead.
 *
 * The rules every entry must keep:
 *
 * - **Unambiguous.** Well-established, uncontroversial facts only. No trick wording, no
 *   "usually", no opinions, nothing that changed recently or depends on a definition people
 *   argue about. Nothing political, religious-controversial, violent, or about living people.
 * - **Plausible falsehoods.** A false statement should sound believable and be clearly
 *   wrong once the explanation is read.
 * - **Short.** Statement: zh ≤ 30, ja ≤ 40, en ≤ 90 characters. Explanation: one
 *   sentence, zh ≤ 40, en ≤ 120 characters.
 * - **Balanced.** Keep true and false roughly even, and the category mix roughly as it is.
 * - **`island` is this island.** Those entries may only use facts that are true in the
 *   game world (the map in `maps/nagisa-island.ts`, the clock in `island-time.ts`).
 */

/** One ○× statement. `answer: true` means ○ (the statement is correct). */
export interface QuizQuestion {
  /** Stable id, kebab-case, unique. Never reuse or renumber — ids travel on the wire. */
  readonly id: string;
  readonly answer: boolean;
  /** Category for balancing. */
  readonly category: 'japan' | 'nature' | 'science' | 'world' | 'food' | 'island';
  /** The statement, in Simplified Chinese / Japanese / English. */
  readonly zh: string;
  readonly ja: string;
  readonly en: string;
  /** One short sentence shown on reveal explaining the answer, same three languages. */
  readonly explain: { readonly zh: string; readonly ja: string; readonly en: string };
}

export const QUIZ_BANK: readonly QuizQuestion[] = [
  // ═══ Japan: culture, customs, geography, language ═══════════════════════
  {
    id: 'japan-fuji-highest',
    answer: true,
    category: 'japan',
    zh: '富士山是日本最高的山',
    ja: '富士山は日本で一番高い山である',
    en: 'Mount Fuji is the highest mountain in Japan',
    explain: {
      zh: '富士山海拔3776米，是日本最高峰。',
      ja: '富士山は標高3776mで、日本の最高峰。',
      en: 'At 3,776 m, Mount Fuji is the highest peak in Japan.',
    },
  },
  {
    id: 'japan-fuji-extinct',
    answer: false,
    category: 'japan',
    zh: '富士山是一座死火山',
    ja: '富士山は死火山である',
    en: 'Mount Fuji is an extinct volcano',
    explain: {
      zh: '富士山是活火山，最近一次喷发在1707年。',
      ja: '富士山は活火山で、最後の噴火は1707年。',
      en: 'Mount Fuji is an active volcano; it last erupted in 1707.',
    },
  },
  {
    id: 'japan-aomori-northernmost',
    answer: false,
    category: 'japan',
    zh: '青森县是日本最北端的都道府县',
    ja: '青森県は日本で最も北にある都道府県である',
    en: "Aomori is Japan's northernmost prefecture",
    explain: {
      zh: '最北端的是北海道，青森县是本州最北的县。',
      ja: '最も北にあるのは北海道で、青森県は本州の最北端。',
      en: 'Hokkaido lies further north; Aomori is the northernmost prefecture on Honshu.',
    },
  },
  {
    id: 'japan-hokkaido-largest-island',
    answer: false,
    category: 'japan',
    zh: '北海道是日本面积最大的岛',
    ja: '北海道は日本で一番大きい島である',
    en: "Hokkaido is Japan's largest island",
    explain: {
      zh: '面积最大的岛是本州，北海道排第二。',
      ja: '一番大きい島は本州で、北海道は2番目。',
      en: 'Honshu is the largest island; Hokkaido is second.',
    },
  },
  {
    id: 'japan-shikoku-smallest',
    answer: true,
    category: 'japan',
    zh: '四国是日本四大岛中最小的',
    ja: '四国は日本の主な4つの島の中で一番小さい',
    en: "Shikoku is the smallest of Japan's four main islands",
    explain: {
      zh: '四大岛按面积依次是本州、北海道、九州、四国。',
      ja: '面積の順に本州、北海道、九州、四国となる。',
      en: 'By area they rank Honshu, Hokkaido, Kyushu, then Shikoku.',
    },
  },
  {
    id: 'japan-biwa-largest-lake',
    answer: true,
    category: 'japan',
    zh: '琵琶湖是日本最大的湖',
    ja: '琵琶湖は日本最大の湖である',
    en: "Lake Biwa is Japan's largest lake",
    explain: {
      zh: '琵琶湖位于滋贺县，面积约670平方公里。',
      ja: '琵琶湖は滋賀県にあり、面積は約670km²。',
      en: 'Lake Biwa lies in Shiga Prefecture and covers about 670 km².',
    },
  },
  {
    id: 'japan-shinano-longest-river',
    answer: true,
    category: 'japan',
    zh: '日本最长的河流是信浓川',
    ja: '日本で一番長い川は信濃川である',
    en: 'The Shinano is the longest river in Japan',
    explain: {
      zh: '信浓川全长约367公里，流经长野县和新潟县。',
      ja: '信濃川は全長約367kmで、長野県と新潟県を流れる。',
      en: 'The Shinano runs about 367 km through Nagano and Niigata.',
    },
  },
  {
    id: 'japan-osaka-kyushu',
    answer: false,
    category: 'japan',
    zh: '大阪位于九州',
    ja: '大阪は九州にある',
    en: 'Osaka is on the island of Kyushu',
    explain: {
      zh: '大阪位于本州的近畿地区。',
      ja: '大阪は本州の近畿地方にある。',
      en: 'Osaka is in the Kinki (Kansai) region of Honshu.',
    },
  },
  {
    id: 'japan-shinkansen-1964',
    answer: true,
    category: 'japan',
    zh: '日本的新干线最早于1964年开通',
    ja: '新幹線が最初に開業したのは1964年である',
    en: 'The first Shinkansen line opened in 1964',
    explain: {
      zh: '东海道新干线于1964年10月开通，就在东京奥运会前。',
      ja: '東海道新幹線は1964年10月、東京五輪の直前に開業した。',
      en: 'The Tokaido Shinkansen opened in October 1964, just before the Tokyo Olympics.',
    },
  },
  {
    id: 'japan-drive-left',
    answer: true,
    category: 'japan',
    zh: '在日本，汽车靠左行驶',
    ja: '日本では車は道路の左側を走る',
    en: 'In Japan, cars drive on the left',
    explain: {
      zh: '日本和英国等国家一样，实行左侧通行。',
      ja: '日本はイギリスなどと同じく左側通行。',
      en: 'Like the UK, Japan keeps to the left side of the road.',
    },
  },
  {
    id: 'japan-school-year-april',
    answer: true,
    category: 'japan',
    zh: '日本学校的新学年从4月开始',
    ja: '日本の学校の新年度は4月に始まる',
    en: 'In Japan, the school year starts in April',
    explain: {
      zh: '日本的学年从4月开始，到次年3月结束。',
      ja: '学年は4月に始まり、翌年の3月に終わる。',
      en: 'The Japanese school year runs from April to the following March.',
    },
  },
  {
    id: 'japan-golden-week-august',
    answer: false,
    category: 'japan',
    zh: '日本的黄金周在8月',
    ja: 'ゴールデンウィークは8月にある',
    en: "Japan's Golden Week holidays are in August",
    explain: {
      zh: '黄金周在4月底到5月初。',
      ja: 'ゴールデンウィークは4月末から5月初め。',
      en: 'Golden Week runs from late April to early May.',
    },
  },
  {
    id: 'japan-hinamatsuri-may',
    answer: false,
    category: 'japan',
    zh: '日本的女儿节（雏祭）在5月5日',
    ja: 'ひな祭りは5月5日である',
    en: "Japan's Doll Festival, Hinamatsuri, is on 5 May",
    explain: {
      zh: '女儿节在3月3日，5月5日是儿童节。',
      ja: 'ひな祭りは3月3日。5月5日はこどもの日。',
      en: "Hinamatsuri is on 3 March; 5 May is Children's Day.",
    },
  },
  {
    id: 'japan-setsubun-beans',
    answer: true,
    category: 'japan',
    zh: '日本节分有撒豆子驱鬼的习俗',
    ja: '節分には豆をまいて鬼を追い払う風習がある',
    en: 'On Setsubun, there is a custom of throwing beans to drive away demons',
    explain: {
      zh: '人们一边喊“鬼出去，福进来”一边撒豆子。',
      ja: '「鬼は外、福は内」と言いながら豆をまく。',
      en: 'People throw roasted beans while calling out "Demons out, good luck in!"',
    },
  },
  {
    id: 'japan-new-year-lunar',
    answer: false,
    category: 'japan',
    zh: '日本人按农历过新年',
    ja: '日本の正月は旧暦で祝う',
    en: 'Japan celebrates New Year by the lunar calendar',
    explain: {
      zh: '日本在1873年改用公历，在1月1日过新年。',
      ja: '日本は1873年に新暦へ改め、正月は1月1日に祝う。',
      en: 'Japan switched to the Western calendar in 1873 and celebrates New Year on 1 January.',
    },
  },
  {
    id: 'japan-tipping-customary',
    answer: false,
    category: 'japan',
    zh: '在日本的餐厅，给小费是惯例',
    ja: '日本の飲食店ではチップを渡すのが習慣である',
    en: 'Tipping at restaurants is customary in Japan',
    explain: {
      zh: '日本的餐厅没有给小费的习惯。',
      ja: '日本の飲食店にはチップの習慣がない。',
      en: 'Tipping is not part of restaurant culture in Japan.',
    },
  },
  {
    id: 'japan-outlet-220v',
    answer: false,
    category: 'japan',
    zh: '日本家用插座的标准电压是220伏',
    ja: '日本の家庭用コンセントの標準電圧は220Vである',
    en: 'Standard household outlets in Japan supply 220 volts',
    explain: {
      zh: '日本家用插座的标准电压是100伏。',
      ja: '日本の家庭用コンセントの標準電圧は100V。',
      en: 'Standard household outlets in Japan supply 100 volts.',
    },
  },
  {
    id: 'japan-frequency-east-west',
    answer: true,
    category: 'japan',
    zh: '日本东部和西部的电源频率不同',
    ja: '東日本と西日本では電気の周波数が違う',
    en: 'Eastern and western Japan use different mains electricity frequencies',
    explain: {
      zh: '东日本用50赫兹，西日本用60赫兹。',
      ja: '東日本は50Hz、西日本は60Hz。',
      en: 'Eastern Japan uses 50 Hz and western Japan uses 60 Hz.',
    },
  },
  {
    id: 'japan-haiku-575',
    answer: true,
    category: 'japan',
    zh: '俳句的基本形式是五七五共17个音',
    ja: '俳句の基本の形は五・七・五の十七音である',
    en: 'The basic haiku form is 17 sounds in a 5-7-5 pattern',
    explain: {
      zh: '俳句由5音、7音、5音三段组成。',
      ja: '俳句は5音・7音・5音の三つの句でできている。',
      en: 'A haiku is built from three parts of 5, 7 and 5 sounds.',
    },
  },
  {
    id: 'japan-kabuki-women',
    answer: false,
    category: 'japan',
    zh: '歌舞伎传统上全部由女性演出',
    ja: '歌舞伎は伝統的に女性だけで演じられる',
    en: 'Kabuki is traditionally performed only by women',
    explain: {
      zh: '歌舞伎传统上由男演员演出，女角由“女形”扮演。',
      ja: '歌舞伎は男性が演じ、女性の役も女形が演じる。',
      en: 'Kabuki actors are traditionally men; male "onnagata" actors play the female roles.',
    },
  },
  {
    id: 'japan-hiragana-26',
    answer: false,
    category: 'japan',
    zh: '平假名一共有26个',
    ja: 'ひらがなは全部で26文字である',
    en: 'There are 26 hiragana characters',
    explain: {
      zh: '基本平假名有46个，26是英文字母的数量。',
      ja: '基本のひらがなは46文字。26はアルファベットの数。',
      en: 'There are 46 basic hiragana; 26 is the number of letters in the English alphabet.',
    },
  },
  {
    id: 'japan-konnichiwa-wa',
    answer: true,
    category: 'japan',
    zh: '「こんにちは」中的「は」读作wa',
    ja: '「こんにちは」の「は」は「わ」と読む',
    en: 'In "konnichiwa" (こんにちは), the kana は is read "wa"',
    explain: {
      zh: '这里的「は」原本是助词，助词「は」读作wa。',
      ja: 'この「は」はもともと助詞で、助詞の「は」は「わ」と読む。',
      en: 'This は was originally the particle は, which is pronounced "wa".',
    },
  },
  {
    id: 'japan-katakana-loanwords',
    answer: true,
    category: 'japan',
    zh: '日语用片假名书写外来语',
    ja: '外来語はカタカナで書き表す',
    en: 'Japanese uses katakana to write foreign loanwords',
    explain: {
      zh: '例如“咖啡”写作片假名「コーヒー」。',
      ja: '例えば「コーヒー」はカタカナで書く。',
      en: 'For example, "coffee" is written in katakana as コーヒー.',
    },
  },
  {
    id: 'japan-tokyo-tower-taller',
    answer: false,
    category: 'japan',
    zh: '东京塔比东京晴空塔高',
    ja: '東京タワーは東京スカイツリーより高い',
    en: 'Tokyo Tower is taller than Tokyo Skytree',
    explain: {
      zh: '晴空塔高634米，东京塔高333米。',
      ja: 'スカイツリーは634m、東京タワーは333m。',
      en: 'Tokyo Skytree is 634 m tall; Tokyo Tower is 333 m.',
    },
  },
  {
    id: 'japan-five-yen-hole',
    answer: true,
    category: 'japan',
    zh: '日本的5日元硬币中间有一个孔',
    ja: '5円玉には真ん中に穴が開いている',
    en: 'The Japanese 5-yen coin has a hole in the middle',
    explain: {
      zh: '5日元和50日元硬币的中间都有孔。',
      ja: '5円玉と50円玉には、どちらも穴が開いている。',
      en: 'Both the 5-yen and the 50-yen coins have a hole in the centre.',
    },
  },

  // ═══ Nature: ocean, animals, plants ═════════════════════════════════════
  {
    id: 'nature-octopus-arms',
    answer: false,
    category: 'nature',
    zh: '章鱼有六条腕',
    ja: 'タコの足は6本である',
    en: 'An octopus has six arms',
    explain: {
      zh: '章鱼有八条腕。',
      ja: 'タコの足は8本。',
      en: 'An octopus has eight arms.',
    },
  },
  {
    id: 'nature-octopus-hearts',
    answer: true,
    category: 'nature',
    zh: '章鱼有三颗心脏',
    ja: 'タコには心臓が3つある',
    en: 'An octopus has three hearts',
    explain: {
      zh: '一颗向全身输送血液，两颗向鳃输送血液。',
      ja: '全身に血を送る心臓が1つ、えらに送る心臓が2つある。',
      en: 'One pumps blood around the body and two pump it through the gills.',
    },
  },
  {
    id: 'nature-whale-fish',
    answer: false,
    category: 'nature',
    zh: '鲸属于鱼类',
    ja: 'クジラは魚の仲間である',
    en: 'Whales are a kind of fish',
    explain: {
      zh: '鲸用肺呼吸、用乳汁哺育幼崽，是哺乳动物。',
      ja: 'クジラは肺で呼吸し、子に乳を与える哺乳類。',
      en: 'Whales are mammals: they breathe with lungs and feed their young milk.',
    },
  },
  {
    id: 'nature-seahorse-male',
    answer: true,
    category: 'nature',
    zh: '海马是由雄性怀卵并生下小海马的',
    ja: 'タツノオトシゴは、オスが卵を抱えて子を産む',
    en: 'In seahorses, the male carries the eggs and gives birth',
    explain: {
      zh: '雌海马把卵产进雄海马的育儿袋里孵化。',
      ja: 'メスがオスの育児のうに卵を産み、そこでかえる。',
      en: "The female lays her eggs in the male's brood pouch, where they develop until birth.",
    },
  },
  {
    id: 'nature-penguin-arctic',
    answer: false,
    category: 'nature',
    zh: '野生企鹅生活在北极',
    ja: '野生のペンギンは北極にすんでいる',
    en: 'Wild penguins live in the Arctic',
    explain: {
      zh: '野生企鹅几乎都生活在南半球，北极没有企鹅。',
      ja: '野生のペンギンはほぼ南半球にすみ、北極にはいない。',
      en: 'Wild penguins live almost entirely in the Southern Hemisphere; there are none in the Arctic.',
    },
  },
  {
    id: 'nature-spider-insect',
    answer: false,
    category: 'nature',
    zh: '蜘蛛是昆虫',
    ja: 'クモは昆虫である',
    en: 'Spiders are insects',
    explain: {
      zh: '蜘蛛有八条腿，属于蛛形纲，不是昆虫。',
      ja: 'クモは足が8本のクモ類で、昆虫ではない。',
      en: 'Spiders have eight legs and are arachnids, not insects.',
    },
  },
  {
    id: 'nature-bamboo-grass',
    answer: true,
    category: 'nature',
    zh: '竹子属于禾本科植物',
    ja: '竹はイネ科の植物である',
    en: 'Bamboo belongs to the grass family',
    explain: {
      zh: '竹子和水稻、小麦同属禾本科。',
      ja: '竹はイネや麦と同じイネ科の植物。',
      en: 'Bamboo is in the same family as rice and wheat: the grasses.',
    },
  },
  {
    id: 'nature-shark-cartilage',
    answer: true,
    category: 'nature',
    zh: '鲨鱼的骨骼是由软骨构成的',
    ja: 'サメの骨格は軟骨でできている',
    en: "A shark's skeleton is made of cartilage",
    explain: {
      zh: '鲨鱼属于软骨鱼类，骨架中没有硬骨。',
      ja: 'サメは軟骨魚類で、骨格に硬い骨がない。',
      en: 'Sharks are cartilaginous fish, with no bony skeleton.',
    },
  },
  {
    id: 'nature-coral-plant',
    answer: false,
    category: 'nature',
    zh: '珊瑚是一种植物',
    ja: 'サンゴは植物である',
    en: 'Coral is a plant',
    explain: {
      zh: '珊瑚是动物，和水母同属刺胞动物。',
      ja: 'サンゴは動物で、クラゲと同じ刺胞動物。',
      en: 'Corals are animals, close relatives of jellyfish.',
    },
  },
  {
    id: 'nature-bat-bird',
    answer: false,
    category: 'nature',
    zh: '蝙蝠是鸟类',
    ja: 'コウモリは鳥の仲間である',
    en: 'Bats are birds',
    explain: {
      zh: '蝙蝠是会飞的哺乳动物。',
      ja: 'コウモリは空を飛ぶ哺乳類。',
      en: 'Bats are mammals that can fly.',
    },
  },
  {
    id: 'nature-cherry-rose-family',
    answer: true,
    category: 'nature',
    zh: '樱花树属于蔷薇科植物',
    ja: '桜はバラ科の植物である',
    en: 'Cherry trees belong to the rose family',
    explain: {
      zh: '樱花和梅、桃、苹果一样属于蔷薇科。',
      ja: '桜は梅や桃、リンゴと同じバラ科。',
      en: 'Cherries share the rose family with plums, peaches and apples.',
    },
  },
  {
    id: 'nature-giraffe-neck-seven',
    answer: true,
    category: 'nature',
    zh: '长颈鹿的颈椎和人一样是7块',
    ja: 'キリンの首の骨は人と同じ7個である',
    en: 'A giraffe has seven neck vertebrae, the same as a human',
    explain: {
      zh: '长颈鹿颈椎数量和人一样，只是每一块都特别长。',
      ja: 'キリンの首の骨は数は人と同じで、一つ一つがとても長い。',
      en: "A giraffe's neck vertebrae are no more numerous than ours, just much longer.",
    },
  },
  {
    id: 'nature-butterfly-taste-feet',
    answer: true,
    category: 'nature',
    zh: '蝴蝶能用脚尝出味道',
    ja: 'チョウは足で味を感じることができる',
    en: 'Butterflies can taste with their feet',
    explain: {
      zh: '蝴蝶的脚上长着能感知味道的感受器。',
      ja: 'チョウの足には味を感じる器官がある。',
      en: 'Butterflies have taste receptors on their feet.',
    },
  },
  {
    id: 'nature-sea-turtle-beach',
    answer: true,
    category: 'nature',
    zh: '海龟会爬上沙滩产卵',
    ja: 'ウミガメは砂浜に上がって卵を産む',
    en: 'Sea turtles come ashore to lay their eggs on sandy beaches',
    explain: {
      zh: '雌海龟会在沙滩上挖洞，把卵产在里面。',
      ja: 'メスが砂浜に穴を掘り、そこに卵を産む。',
      en: 'Female sea turtles dig nests in the sand and lay their eggs there.',
    },
  },
  {
    id: 'nature-koala-bear',
    answer: false,
    category: 'nature',
    zh: '考拉是熊的一种',
    ja: 'コアラはクマの仲間である',
    en: 'Koalas are a kind of bear',
    explain: {
      zh: '考拉是用育儿袋养育幼崽的有袋类动物。',
      ja: 'コアラはお腹の袋で子を育てる有袋類。',
      en: 'Koalas are marsupials that raise their young in a pouch.',
    },
  },

  // ═══ Science ═════════════════════════════════════════════════════════════
  {
    id: 'science-light-faster-than-sound',
    answer: true,
    category: 'science',
    zh: '光的传播速度比声音快',
    ja: '光は音よりも速く伝わる',
    en: 'Light travels faster than sound',
    explain: {
      zh: '所以打雷时，总是先看到闪电再听到雷声。',
      ja: 'だから雷は、光が先に見えて音が後から聞こえる。',
      en: 'That is why you see lightning before you hear the thunder.',
    },
  },
  {
    id: 'science-mars-iron-oxide',
    answer: true,
    category: 'science',
    zh: '火星呈红色是因为表面有氧化铁',
    ja: '火星が赤く見えるのは表面に酸化鉄があるからだ',
    en: 'Mars looks red because of iron oxide on its surface',
    explain: {
      zh: '氧化铁就是铁锈，它覆盖着火星的岩石和沙尘。',
      ja: '酸化鉄はいわば鉄さびで、火星の岩や砂を覆っている。',
      en: "Iron oxide is essentially rust, and it coats Mars's rocks and dust.",
    },
  },
  {
    id: 'science-diamond-carbon',
    answer: true,
    category: 'science',
    zh: '钻石是由碳元素构成的',
    ja: 'ダイヤモンドは炭素でできている',
    en: 'Diamonds are made of carbon',
    explain: {
      zh: '钻石和石墨都由碳构成，只是原子排列不同。',
      ja: 'ダイヤモンドも黒鉛も炭素で、原子の並び方が違うだけ。',
      en: 'Diamond and graphite are both carbon; only the arrangement of their atoms differs.',
    },
  },
  {
    id: 'science-sound-faster-in-water',
    answer: true,
    category: 'science',
    zh: '声音在水中比在空气中传得快',
    ja: '音は空気中より水中の方が速く伝わる',
    en: 'Sound travels faster in water than in air',
    explain: {
      zh: '水中声速约每秒1500米，是空气中的4倍多。',
      ja: '水中の音速は秒速約1500mで、空気中の4倍以上。',
      en: 'Sound moves at about 1,500 m/s in water, over four times its speed in air.',
    },
  },
  {
    id: 'science-venus-hottest',
    answer: true,
    category: 'science',
    zh: '金星是太阳系中表面温度最高的行星',
    ja: '金星は太陽系で表面温度が最も高い惑星である',
    en: 'Venus has the hottest surface of any planet in the Solar System',
    explain: {
      zh: '浓厚的二氧化碳大气使金星表面超过400℃。',
      ja: '厚い二酸化炭素の大気のため、表面は400℃を超える。',
      en: 'Its thick carbon dioxide atmosphere traps heat, keeping the surface above 400 °C.',
    },
  },
  {
    id: 'science-tides-moon-sun',
    answer: true,
    category: 'science',
    zh: '潮汐是由月球和太阳的引力引起的',
    ja: '潮の満ち引きは月と太陽の引力によって起こる',
    en: 'Tides are caused by the gravity of the Moon and the Sun',
    explain: {
      zh: '其中月球的影响更大，约是太阳的两倍。',
      ja: '影響は月の方が大きく、太陽の約2倍ある。',
      en: "The Moon's pull matters more, about twice as much as the Sun's.",
    },
  },
  {
    id: 'science-mercury-liquid',
    answer: true,
    category: 'science',
    zh: '金属水银在常温下是液体',
    ja: '金属の水銀は常温で液体である',
    en: 'The metal mercury is a liquid at room temperature',
    explain: {
      zh: '水银的熔点约为零下39℃，所以常温下是液态。',
      ja: '水銀の融点は約マイナス39℃なので、常温では液体。',
      en: 'Mercury melts at about −39 °C, so it stays liquid at room temperature.',
    },
  },
  {
    id: 'science-boiling-point-altitude',
    answer: false,
    category: 'science',
    zh: '海拔越高，水的沸点越高',
    ja: '標高が高いほど、水の沸点は高くなる',
    en: 'The higher the altitude, the higher the boiling point of water',
    explain: {
      zh: '高处气压低，水的沸点反而会降低。',
      ja: '高い所は気圧が低いので、沸点はむしろ下がる。',
      en: 'Air pressure drops with altitude, so water boils at a lower temperature.',
    },
  },
  {
    id: 'science-sound-in-vacuum',
    answer: false,
    category: 'science',
    zh: '声音可以在真空中传播',
    ja: '音は真空中でも伝わる',
    en: 'Sound can travel through a vacuum',
    explain: {
      zh: '声音需要空气、水等介质才能传播。',
      ja: '音は空気や水などの物質がないと伝わらない。',
      en: 'Sound needs a medium such as air or water to travel.',
    },
  },
  {
    id: 'science-moon-own-light',
    answer: false,
    category: 'science',
    zh: '月亮自己会发光',
    ja: '月は自ら光を出して輝いている',
    en: 'The Moon shines with its own light',
    explain: {
      zh: '月光是月球表面反射的太阳光。',
      ja: '月の光は、太陽の光を月の表面が反射したもの。',
      en: "Moonlight is sunlight reflected off the Moon's surface.",
    },
  },
  {
    id: 'science-saturn-largest',
    answer: false,
    category: 'science',
    zh: '土星是太阳系中最大的行星',
    ja: '土星は太陽系で一番大きい惑星である',
    en: 'Saturn is the largest planet in the Solar System',
    explain: {
      zh: '最大的行星是木星，土星排第二。',
      ja: '一番大きいのは木星で、土星は2番目。',
      en: 'Jupiter is the largest planet; Saturn is second.',
    },
  },
  {
    id: 'science-air-mostly-oxygen',
    answer: false,
    category: 'science',
    zh: '空气中含量最多的气体是氧气',
    ja: '空気に最も多く含まれる気体は酸素である',
    en: 'Oxygen is the most abundant gas in the air',
    explain: {
      zh: '氮气约占空气的78%，氧气只占约21%。',
      ja: '空気の約78%は窒素で、酸素は約21%。',
      en: 'Nitrogen makes up about 78% of the air; oxygen only about 21%.',
    },
  },
  {
    id: 'science-ice-denser',
    answer: false,
    category: 'science',
    zh: '冰的密度比液态水大',
    ja: '氷は液体の水より密度が大きい',
    en: 'Ice is denser than liquid water',
    explain: {
      zh: '冰的密度比水小，所以冰会浮在水面上。',
      ja: '氷は水より密度が小さいので、水に浮く。',
      en: 'Ice is less dense than water, which is why it floats.',
    },
  },
  {
    id: 'science-seasons-distance',
    answer: false,
    category: 'science',
    zh: '四季变化是因为地球与太阳的距离在变',
    ja: '季節が変わるのは地球と太陽の距離が変わるからだ',
    en: "Seasons happen because Earth's distance from the Sun changes",
    explain: {
      zh: '季节由地轴倾斜造成，地球在1月初反而离太阳最近。',
      ja: '季節の原因は地軸の傾きで、地球は1月初めに太陽に最も近い。',
      en: "Seasons come from Earth's tilted axis; Earth is actually closest to the Sun in early January.",
    },
  },
  {
    id: 'science-sky-reflects-sea',
    answer: false,
    category: 'science',
    zh: '天空是蓝色的，是因为映出了大海的颜色',
    ja: '空が青いのは、海の色が映っているからだ',
    en: 'The sky is blue because it reflects the colour of the sea',
    explain: {
      zh: '大气对阳光中的蓝光散射得最强，所以天空是蓝色。',
      ja: '大気が太陽光の青い光を強く散乱させるため、空は青い。',
      en: 'Air scatters the blue part of sunlight more than other colours, which makes the sky blue.',
    },
  },

  // ═══ World: geography and history ═══════════════════════════════════════
  {
    id: 'world-pacific-largest',
    answer: true,
    category: 'world',
    zh: '太平洋是世界上面积最大的大洋',
    ja: '太平洋は世界で一番広い海洋である',
    en: 'The Pacific is the largest ocean in the world',
    explain: {
      zh: '太平洋比地球上所有陆地加起来还要大。',
      ja: '太平洋は、地球の陸地を全部合わせたよりも広い。',
      en: "The Pacific is larger than all of Earth's land put together.",
    },
  },
  {
    id: 'world-nile-egypt',
    answer: true,
    category: 'world',
    zh: '尼罗河流经埃及',
    ja: 'ナイル川はエジプトを流れている',
    en: 'The Nile flows through Egypt',
    explain: {
      zh: '尼罗河向北流经埃及，注入地中海。',
      ja: 'ナイル川はエジプトを北へ流れ、地中海に注ぐ。',
      en: 'The Nile flows north through Egypt into the Mediterranean Sea.',
    },
  },
  {
    id: 'world-everest-highest',
    answer: true,
    category: 'world',
    zh: '珠穆朗玛峰是世界上海拔最高的山',
    ja: 'エベレストは世界で最も標高が高い山である',
    en: 'Mount Everest is the highest mountain above sea level in the world',
    explain: {
      zh: '珠穆朗玛峰海拔约8849米。',
      ja: 'エベレストの標高は約8849m。',
      en: 'The summit of Everest is about 8,849 m above sea level.',
    },
  },
  {
    id: 'world-eiffel-1889',
    answer: true,
    category: 'world',
    zh: '埃菲尔铁塔建成于1889年',
    ja: 'エッフェル塔は1889年に完成した',
    en: 'The Eiffel Tower was completed in 1889',
    explain: {
      zh: '它是为1889年巴黎世界博览会而建的。',
      ja: '1889年のパリ万国博覧会のために建てられた。',
      en: "It was built for the 1889 World's Fair in Paris.",
    },
  },
  {
    id: 'world-dead-sea-float',
    answer: true,
    category: 'world',
    zh: '在死海里，人很容易浮起来',
    ja: '死海では人の体が簡単に浮く',
    en: 'People float easily in the Dead Sea',
    explain: {
      zh: '死海的盐度极高，水的浮力很大。',
      ja: '死海は塩分がとても濃く、浮力が大きい。',
      en: 'The Dead Sea is so salty that its water holds people up easily.',
    },
  },
  {
    id: 'world-panama-canal',
    answer: true,
    category: 'world',
    zh: '巴拿马运河连接着大西洋和太平洋',
    ja: 'パナマ運河は大西洋と太平洋を結んでいる',
    en: 'The Panama Canal links the Atlantic and Pacific Oceans',
    explain: {
      zh: '船只经由运河，不必绕行南美洲南端。',
      ja: '船は運河を通れば、南米の南端を回らずに済む。',
      en: 'Ships can cross between the two oceans without sailing around South America.',
    },
  },
  {
    id: 'world-olympics-greece',
    answer: true,
    category: 'world',
    zh: '古代奥运会起源于古希腊',
    ja: '古代オリンピックは古代ギリシャで始まった',
    en: 'The ancient Olympic Games began in ancient Greece',
    explain: {
      zh: '古代奥运会在希腊的奥林匹亚举行。',
      ja: '古代オリンピックはギリシャのオリンピアで開かれた。',
      en: 'The ancient Games were held at Olympia, in Greece.',
    },
  },
  {
    id: 'world-moon-landing-1969',
    answer: true,
    category: 'world',
    zh: '人类首次登上月球是在1969年',
    ja: '人類が初めて月に降り立ったのは1969年である',
    en: 'Humans first landed on the Moon in 1969',
    explain: {
      zh: '1969年7月，阿波罗11号实现了载人登月。',
      ja: '1969年7月、アポロ11号が有人月面着陸を果たした。',
      en: 'Apollo 11 landed astronauts on the Moon in July 1969.',
    },
  },
  {
    id: 'world-amazon-africa',
    answer: false,
    category: 'world',
    zh: '亚马孙河位于非洲',
    ja: 'アマゾン川はアフリカにある',
    en: 'The Amazon River is in Africa',
    explain: {
      zh: '亚马孙河位于南美洲。',
      ja: 'アマゾン川は南アメリカを流れている。',
      en: 'The Amazon flows across South America.',
    },
  },
  {
    id: 'world-sahara-asia',
    answer: false,
    category: 'world',
    zh: '撒哈拉沙漠位于亚洲',
    ja: 'サハラ砂漠はアジアにある',
    en: 'The Sahara Desert is in Asia',
    explain: {
      zh: '撒哈拉沙漠位于非洲北部。',
      ja: 'サハラ砂漠はアフリカ北部にある。',
      en: 'The Sahara covers much of northern Africa.',
    },
  },
  {
    id: 'world-giza-pyramids-roman',
    answer: false,
    category: 'world',
    zh: '吉萨金字塔建于古罗马时代',
    ja: 'ギザのピラミッドは古代ローマ時代に造られた',
    en: 'The pyramids of Giza were built in the time of ancient Rome',
    explain: {
      zh: '它们建于约4500年前，远早于古罗马。',
      ja: '約4500年前に造られ、古代ローマよりずっと古い。',
      en: 'They were built about 4,500 years ago, long before Rome existed.',
    },
  },
  {
    id: 'world-north-pole-land',
    answer: false,
    category: 'world',
    zh: '北极点位于陆地上',
    ja: '北極点は陸地の上にある',
    en: 'The North Pole is on land',
    explain: {
      zh: '北极点在北冰洋的中央，下面是海而不是陆地。',
      ja: '北極点は北極海の真ん中にあり、下は陸でなく海。',
      en: 'The North Pole is in the middle of the Arctic Ocean, with sea beneath it, not land.',
    },
  },
  {
    id: 'world-australia-capital-sydney',
    answer: false,
    category: 'world',
    zh: '澳大利亚的首都是悉尼',
    ja: 'オーストラリアの首都はシドニーである',
    en: 'The capital of Australia is Sydney',
    explain: {
      zh: '澳大利亚的首都是堪培拉。',
      ja: 'オーストラリアの首都はキャンベラ。',
      en: "Australia's capital is Canberra.",
    },
  },
  {
    id: 'world-mona-lisa-van-gogh',
    answer: false,
    category: 'world',
    zh: '《蒙娜丽莎》是梵高的作品',
    ja: '『モナ・リザ』はゴッホの作品である',
    en: 'The Mona Lisa was painted by Van Gogh',
    explain: {
      zh: '《蒙娜丽莎》出自列奥纳多·达·芬奇之手。',
      ja: '『モナ・リザ』を描いたのはレオナルド・ダ・ヴィンチ。',
      en: 'The Mona Lisa was painted by Leonardo da Vinci.',
    },
  },
  {
    id: 'world-kilimanjaro-south-america',
    answer: false,
    category: 'world',
    zh: '乞力马扎罗山位于南美洲',
    ja: 'キリマンジャロは南アメリカにある',
    en: 'Mount Kilimanjaro is in South America',
    explain: {
      zh: '乞力马扎罗山位于非洲的坦桑尼亚。',
      ja: 'キリマンジャロはアフリカのタンザニアにある。',
      en: 'Kilimanjaro is in Tanzania, in Africa.',
    },
  },

  // ═══ Food ════════════════════════════════════════════════════════════════
  {
    id: 'food-natto-soybeans',
    answer: true,
    category: 'food',
    zh: '纳豆是用大豆发酵制成的',
    ja: '納豆は大豆を発酵させて作る',
    en: 'Natto is made by fermenting soybeans',
    explain: {
      zh: '把煮熟的大豆用纳豆菌发酵，就成了纳豆。',
      ja: '煮た大豆を納豆菌で発酵させると納豆になる。',
      en: 'Cooked soybeans are fermented with natto bacteria.',
    },
  },
  {
    id: 'food-mochi-glutinous-rice',
    answer: true,
    category: 'food',
    zh: '日本的年糕（餅）是用糯米捣成的',
    ja: '餅はもち米をついて作る',
    en: 'Japanese mochi is made by pounding glutinous rice',
    explain: {
      zh: '把蒸好的糯米捣到又软又黏，就成了年糕。',
      ja: '蒸したもち米を粘りが出るまでつくと餅になる。',
      en: 'Steamed glutinous rice is pounded until it turns smooth and sticky.',
    },
  },
  {
    id: 'food-matcha-green-tea',
    answer: true,
    category: 'food',
    zh: '抹茶是用绿茶的茶叶磨成的粉',
    ja: '抹茶は緑茶の葉をひいて粉にしたものである',
    en: 'Matcha is powder made by grinding green tea leaves',
    explain: {
      zh: '抹茶是把遮光栽培的茶叶磨成细粉制成的。',
      ja: '日光を遮って育てた茶葉を、細かくひいて作る。',
      en: 'It is made by grinding shade-grown tea leaves into a fine powder.',
    },
  },
  {
    id: 'food-chocolate-cacao',
    answer: true,
    category: 'food',
    zh: '巧克力的原料是可可豆',
    ja: 'チョコレートの原料はカカオ豆である',
    en: 'Chocolate is made from cacao beans',
    explain: {
      zh: '可可豆是可可树果实里的种子。',
      ja: 'カカオ豆は、カカオの木の実の中にある種。',
      en: 'Cacao beans are the seeds inside the fruit of the cacao tree.',
    },
  },
  {
    id: 'food-green-black-tea-same-plant',
    answer: true,
    category: 'food',
    zh: '绿茶和红茶来自同一种植物',
    ja: '緑茶と紅茶は同じ植物の葉から作られる',
    en: 'Green tea and black tea come from the same plant',
    explain: {
      zh: '两者都用茶树的叶子，只是加工方法不同。',
      ja: 'どちらもチャノキの葉で、違いは加工の仕方だけ。',
      en: 'Both come from the tea plant; the difference is how the leaves are processed.',
    },
  },
  {
    id: 'food-sushi-always-raw-fish',
    answer: false,
    category: 'food',
    zh: '寿司一定要用生鱼',
    ja: '寿司には必ず生の魚が使われている',
    en: 'Sushi always contains raw fish',
    explain: {
      zh: '寿司指醋饭料理，玉子寿司、黄瓜卷都不用生鱼。',
      ja: '寿司は酢飯の料理で、玉子やかっぱ巻きには生魚を使わない。',
      en: 'Sushi means vinegared rice; egg sushi and cucumber rolls have no raw fish at all.',
    },
  },
  {
    id: 'food-umeboshi-cherries',
    answer: false,
    category: 'food',
    zh: '梅干是用樱桃腌制的',
    ja: '梅干しはサクランボを漬けて作る',
    en: 'Umeboshi are made by pickling cherries',
    explain: {
      zh: '梅干是把梅子的果实用盐腌渍后晒干制成的。',
      ja: '梅干しは、梅の実を塩漬けにして干したもの。',
      en: 'Umeboshi are ume fruits that have been salted and then dried.',
    },
  },
  {
    id: 'food-udon-buckwheat',
    answer: false,
    category: 'food',
    zh: '乌冬面是用荞麦粉做的',
    ja: 'うどんはそば粉で作られている',
    en: 'Udon noodles are made from buckwheat flour',
    explain: {
      zh: '乌冬面用小麦粉制作，用荞麦粉的是荞麦面。',
      ja: 'うどんは小麦粉で作る。そば粉を使うのはそば。',
      en: 'Udon is made from wheat flour; buckwheat is used for soba.',
    },
  },
  {
    id: 'food-potato-europe',
    answer: false,
    category: 'food',
    zh: '土豆原产于欧洲',
    ja: 'ジャガイモの原産地はヨーロッパである',
    en: 'Potatoes originally come from Europe',
    explain: {
      zh: '土豆原产于南美洲的安第斯山区，后来才传入欧洲。',
      ja: '原産地は南米のアンデス地方で、後にヨーロッパへ伝わった。',
      en: 'Potatoes come from the Andes in South America and reached Europe later.',
    },
  },
  {
    id: 'food-pineapple-tree',
    answer: false,
    category: 'food',
    zh: '菠萝是长在树上的',
    ja: 'パイナップルは木になる果物である',
    en: 'Pineapples grow on trees',
    explain: {
      zh: '菠萝长在贴近地面的矮小植株中央。',
      ja: 'パイナップルは、地面近くの低い草の中心に実る。',
      en: 'A pineapple grows from the centre of a low, leafy plant close to the ground.',
    },
  },
  {
    id: 'food-kiwifruit-new-zealand',
    answer: false,
    category: 'food',
    zh: '猕猴桃原产于新西兰',
    ja: 'キウイフルーツの原産地はニュージーランドである',
    en: 'Kiwifruit originally comes from New Zealand',
    explain: {
      zh: '猕猴桃原产于中国，后来在新西兰被改良推广。',
      ja: '原産は中国で、ニュージーランドで改良されて広まった。',
      en: 'Kiwifruit is native to China; New Zealand later improved and popularised it.',
    },
  },
  {
    id: 'food-taiyaki-sea-bream',
    answer: false,
    category: 'food',
    zh: '鲷鱼烧里包着鲷鱼肉',
    ja: 'たい焼きにはタイの身が入っている',
    en: 'Taiyaki are filled with real sea bream',
    explain: {
      zh: '鲷鱼烧只是做成鲷鱼的形状，里面没有鱼。',
      ja: 'たい焼きは形がタイなだけで、魚は入っていない。',
      en: 'Taiyaki are only shaped like sea bream; there is no fish inside.',
    },
  },

  // ═══ Island: facts about this island (true in the game world) ═══════════
  {
    id: 'island-ferry-north-harbour',
    answer: false,
    category: 'island',
    zh: '渡轮停靠在北港',
    ja: 'フェリーは北港に着く',
    en: 'The ferry arrives at the North Harbour',
    explain: {
      zh: '渡轮停靠的是南港。',
      ja: 'フェリーが着くのは南港。',
      en: 'The ferry comes in at the South Harbour.',
    },
  },
  {
    id: 'island-lighthouse-north-west',
    answer: true,
    category: 'island',
    zh: '灯塔位于岛西北方的灯塔岬',
    ja: '灯台は島の北西、灯台岬に立っている',
    en: 'The lighthouse stands on the Lighthouse Cape in the north-west',
    explain: {
      zh: '灯塔岬在岛的西北方，灯塔就立在那里。',
      ja: '灯台岬は島の北西にあり、そこに灯台が立っている。',
      en: 'The Lighthouse Cape is in the north-west of the island, and the lighthouse stands there.',
    },
  },
  {
    id: 'island-shrine-east',
    answer: false,
    category: 'island',
    zh: '神社位于岛的东侧',
    ja: '神社は島の東側にある',
    en: 'The shrine is on the east side of the island',
    explain: {
      zh: '神社在岛的西侧，东侧是广场。',
      ja: '神社は島の西側にあり、東側にあるのは広場。',
      en: 'The shrine is on the west side; the Main Plaza is on the east.',
    },
  },
  {
    id: 'island-plaza-east',
    answer: true,
    category: 'island',
    zh: '广场位于岛的东侧',
    ja: '広場は島の東側にある',
    en: 'The Main Plaza is on the east side of the island',
    explain: {
      zh: '广场就在岛的东侧。',
      ja: '広場は島の東側にある。',
      en: 'The Main Plaza sits on the east side of the island.',
    },
  },
  {
    id: 'island-summit-centre',
    answer: true,
    category: 'island',
    zh: '岛上的山顶位于岛的正中央',
    ja: '山頂は島の真ん中にある',
    en: "The island's summit is in the middle of the island",
    explain: {
      zh: '山顶就在岛的正中央。',
      ja: '山頂は島のちょうど真ん中にある。',
      en: 'The summit sits right in the middle of the island.',
    },
  },
  {
    id: 'island-one-harbour',
    answer: false,
    category: 'island',
    zh: '这座岛上只有一个港口',
    ja: 'この島には港が一つしかない',
    en: 'The island has only one harbour',
    explain: {
      zh: '岛上有南港和北港两个港口。',
      ja: '島には南港と北港の二つの港がある。',
      en: 'The island has two harbours: the South Harbour and the North Harbour.',
    },
  },
  {
    id: 'island-beach-north-harbour',
    answer: false,
    category: 'island',
    zh: '夕阳海滩就在北港旁边',
    ja: '浜（サンセットビーチ）は北港のすぐそばにある',
    en: 'Sunset Beach is right next to the North Harbour',
    explain: {
      zh: '夕阳海滩在岛的东南方，靠近南港。',
      ja: '浜は島の南東、南港の近くにある。',
      en: 'Sunset Beach is in the south-east, near the South Harbour.',
    },
  },
  {
    id: 'island-day-90-minutes',
    answer: true,
    category: 'island',
    zh: '岛上的一天等于现实中的90分钟',
    ja: '島の一日は現実の90分である',
    en: 'One island day lasts 90 real minutes',
    explain: {
      zh: '岛上完整的一轮昼夜，只需现实中的90分钟。',
      ja: '島の昼と夜の一巡りは、現実の90分で終わる。',
      en: 'A full island day-night cycle takes 90 minutes of real time.',
    },
  },
];

const QUIZ_BY_ID: ReadonlyMap<string, QuizQuestion> = new Map(QUIZ_BANK.map((q) => [q.id, q]));

/** Look up by id. */
export function getQuizQuestion(id: string): QuizQuestion | undefined {
  return QUIZ_BY_ID.get(id);
}
